# Generated by Django 2.2.19 on 2024-01-11 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напишите название категорию', max_length=250, verbose_name='Категория')),
                ('slug', models.SlugField(help_text='Напишите URL для тега', unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': ('Категория',),
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напишите название игрушки', max_length=250, verbose_name='Название игрушки')),
                ('slug', models.SlugField(help_text='Напишите URL для игрушки', unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.ForeignKey(blank=True, help_text='Выберите или добавте категорию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toys', to='toys.Category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': ('Игрушка',),
                'verbose_name_plural': 'Игрушки',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напишите название изображения', max_length=250, verbose_name='Название изображения')),
                ('image', models.ImageField(help_text='Загрузите фото игрушки', upload_to='toys_image/', verbose_name='Изображенеи игрушки')),
                ('default', models.BooleanField(default=False)),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toys.Toy')),
            ],
            options={
                'verbose_name': ('Фотография игрушки',),
                'verbose_name_plural': 'Фотографии игрушек',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='toys.Toy', verbose_name='Игрушка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
            },
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'toy'), name='unique_favorites'),
        ),
    ]
